package com.ozdemir.tvlauncher;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.ConnectivityManager;
import android.net.Network;
import android.net.NetworkCapabilities;
import android.os.Bundle;
import android.os.Handler;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class MainActivity extends Activity {
 private final Handler clockHandler=new Handler(); private TextView clockView,dateView,networkView; private LinearLayout root; private SharedPreferences prefs; private int themeIndex;
 private final int[][] themes={{0xFF120818,0xFF2C0E40,0xFF08060E},{0xFF070A1B,0xFF20113D,0xFF08070F},{0xFF090A18,0xFF36144F,0xFF0D0715},{0xFF16071E,0xFF4A1764,0xFF0A0610}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);prefs=getSharedPreferences("ozdemir_tv",MODE_PRIVATE);themeIndex=prefs.getInt("theme",0);hideSystemUi();setContentView(buildHome());startClock();}
 @Override public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)hideSystemUi();} @Override protected void onResume(){super.onResume();themeIndex=prefs.getInt("theme",0);applyTheme();updateNetwork();}
 private void hideSystemUi(){getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}
 private View buildHome(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(34),dp(18),dp(34),dp(18));applyTheme();
  LinearLayout header=row();header.setPadding(dp(4),0,dp(4),0);LinearLayout brandBlock=new LinearLayout(this);brandBlock.setOrientation(LinearLayout.VERTICAL);brandBlock.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("Ö",34,true);brand.setTextColor(0xFFF5E8FF);TextView name=text("ÖZDEMİR",10,true);name.setTextColor(0xFFD6B8EA);name.setLetterSpacing(.16f);brandBlock.addView(brand);brandBlock.addView(name);header.addView(brandBlock,new LinearLayout.LayoutParams(0,dp(66),1f));LinearLayout status=new LinearLayout(this);status.setOrientation(LinearLayout.VERTICAL);status.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);networkView=text("Ağ kontrol ediliyor",13,false);networkView.setGravity(Gravity.RIGHT);status.addView(networkView);header.addView(status,new LinearLayout.LayoutParams(dp(300),dp(66)));LinearLayout time=new LinearLayout(this);time.setOrientation(LinearLayout.VERTICAL);time.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);clockView=text("--:--",27,true);clockView.setGravity(Gravity.RIGHT);dateView=text("",11,false);dateView.setTextColor(0xFFC2ADC9);dateView.setGravity(Gravity.RIGHT);time.addView(clockView);time.addView(dateView);header.addView(time,new LinearLayout.LayoutParams(dp(132),dp(66)));root.addView(header);
  root.addView(section("Ana"));LinearLayout main=row();main.addView(heroCard("▣","Canlı TV","Kanallar ve canlı yayın",this::openLiveTv),weightCard(8,7));main.addView(heroCard("◆","Dizi & Film","Ücretsiz • resmî içerikler",this::openDiziFilm),weightCard(8,7));main.addView(heroCard("▶","SmartTube","YouTube • reklamsız izleme",()->launchFirst(new String[]{"org.smarttuber.stable","com.teamsmart.videomanager.tv"},"SmartTube kurulu değil.")),weightCard(8,7));main.addView(heroCard("◉","coji","Web ve içerik merkezi",()->launchFirst(new String[]{"com.tv.browser","nl.studio.tvLite"},"coji uygulaması bulunamadı.")),weightCard(8,7));main.addView(heroCard("▤","Medya","USB • video • fotoğraf",this::openFiles),weightCard(8,7));root.addView(main,new LinearLayout.LayoutParams(-1,0,1.9f));
  root.addView(section("Çocuklar"));LinearLayout kids=row();kids.addView(kidCard("▶","YouTube Kids",0,()->launchFirst(new String[]{"com.google.android.apps.youtube.kids","com.google.android.youtube.tvkids"},"YouTube Kids kurulu değil.")),weightCard(5,5));kids.addView(kidCard("★","TRT Çocuk",1,()->launchFirst(new String[]{"com.trtcocuk.mobile","com.trtcocuk"},"TRT Çocuk kurulu değil.")),weightCard(5,5));kids.addView(kidCard("●","Bluey",2,()->missing("Bluey içeriği bağlanacak.")),weightCard(5,5));kids.addView(kidCard("♥","Maşa",3,()->missing("Maşa ile Koca Ayı içeriği bağlanacak.")),weightCard(5,5));kids.addView(kidCard("✦","Eğitici & Eğlenceli",4,()->missing("2–5 yaş eğitici içerikleri bağlanacak.")),weightCard(5,5));kids.addView(kidCard("→","Tümünü Gör",5,()->missing("Çocuk içerik ekranı hazırlanacak.")),weightCard(5,5));root.addView(kids,new LinearLayout.LayoutParams(-1,0,1.18f));
  root.addView(section("Sistem"));LinearLayout bottom=row();bottom.addView(systemCard("▦","Uygulamalar",this::openApps),weightCard(4,4));bottom.addView(systemCard("▤","Dosyalar",this::openFiles),weightCard(4,4));bottom.addView(systemCard("⌁","Ağ",()->openPanel("network")),weightCard(4,4));bottom.addView(systemCard("◫","Depolama",()->openPanel("storage")),weightCard(4,4));bottom.addView(systemCard("◷","Zamanlayıcı",()->openPanel("timer")),weightCard(4,4));bottom.addView(systemCard("✦","Tema",()->openPanel("theme")),weightCard(4,4));bottom.addView(systemCard("⚙","Ayarlar",()->openPanel("settings")),weightCard(4,4));bottom.addView(systemCard("⏻","Güç",()->openPanel("power")),weightCard(4,4));root.addView(bottom,new LinearLayout.LayoutParams(-1,0,.93f));View first=main.getChildAt(0);if(first!=null)first.requestFocus();return root;}
 private View heroCard(String icon,String title,String sub,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(22),dp(16),dp(18),dp(14));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(heroBackground(false));box.setElevation(dp(3));TextView i=text(icon,25,true);i.setTextColor(0xFFE8C7FF);box.addView(i);TextView t=text(title,21,true);t.setPadding(0,dp(8),0,0);box.addView(t);TextView s=text(sub,11,false);s.setTextColor(0xFFBCAAC6);s.setPadding(0,dp(5),0,0);s.setSingleLine(true);box.addView(s);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.06f:1f).scaleY(f?1.06f:1f).translationY(f?-dp(3):0).setDuration(130).start();v.setBackground(heroBackground(f));v.setElevation(f?dp(18):dp(3));i.setTextColor(f?Color.WHITE:0xFFE8C7FF);});return box;}
 private View kidCard(String icon,String title,int style,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(12),dp(9),dp(12),dp(9));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(kidBackground(style,false));box.setElevation(dp(2));TextView i=text(icon,20,true);i.setGravity(Gravity.CENTER);i.setTextColor(0xFFFFF3FF);box.addView(i);TextView t=text(title,13,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(4),0,0);t.setSingleLine(true);box.addView(t);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.07f:1f).scaleY(f?1.07f:1f).translationY(f?-dp(2):0).setDuration(120).start();v.setBackground(kidBackground(style,f));v.setElevation(f?dp(14):dp(2));});return box;}
 private View systemCard(String icon,String title,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(10),dp(8),dp(10),dp(8));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(systemBackground(false));box.setElevation(dp(1));TextView i=text(icon,18,true);i.setGravity(Gravity.CENTER);i.setTextColor(0xFFDCC7E8);box.addView(i);TextView t=text(title,12,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(4),0,0);t.setSingleLine(true);box.addView(t);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.06f:1f).scaleY(f?1.06f:1f).translationY(f?-dp(2):0).setDuration(110).start();v.setBackground(systemBackground(f));v.setElevation(f?dp(12):dp(1));i.setTextColor(f?Color.WHITE:0xFFDCC7E8);});return box;}
 private GradientDrawable systemBackground(boolean f){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?new int[]{0xE95D2A83,0xE9361A52}:new int[]{0xB91F1729,0xA915111D});d.setCornerRadius(dp(14));d.setStroke(dp(f?2:1),f?0xFFEBD7F7:0x554D3A59);return d;}
 private GradientDrawable kidBackground(int style,boolean f){int[][] normal={{0xD93D1B5B,0xD926123B},{0xD92D255F,0xD91B173C},{0xD91B3562,0xD9112342},{0xD95A2149,0xD9361530},{0xD947275C,0xD9251739},{0xD92E2346,0xD91B152B}};int[][] focused={{0xFFB33A89,0xFF6A1D70},{0xFF5E54C8,0xFF352D88},{0xFF3386C8,0xFF21518C},{0xFFC9467C,0xFF7B2854},{0xFF8B55C8,0xFF553182},{0xFF7058A6,0xFF403163}};GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?focused[style]:normal[style]);d.setCornerRadius(dp(18));d.setStroke(dp(f?2:1),f?0xFFFFFFFF:0x557D5B86);return d;}
 private GradientDrawable heroBackground(boolean f){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?new int[]{0xFF7A25C8,0xFF4B137A,0xFF28103B}:new int[]{0xE02B183A,0xD0191025,0xC80F0B16});d.setCornerRadius(dp(20));d.setStroke(dp(f?2:1),f?0xFFF3D9FF:0x706D4780);return d;}
 private void nextTheme(){themeIndex=(themeIndex+1)%themes.length;prefs.edit().putInt("theme",themeIndex).apply();applyTheme();Toast.makeText(this,"Tema "+(themeIndex+1)+"/4",Toast.LENGTH_SHORT).show();}private void applyTheme(){if(root==null)return;root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,themes[themeIndex]));}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private LinearLayout.LayoutParams weightCard(int h,int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1f);p.setMargins(dp(h),dp(v),dp(h),dp(v));return p;}private TextView section(String s){TextView t=text(s,14,true);t.setTextColor(0xFFD8B8E9);t.setGravity(Gravity.BOTTOM|Gravity.LEFT);t.setPadding(dp(8),dp(5),0,0);t.setLetterSpacing(.025f);return t;}private TextView text(String s,int sp,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextColor(0xFFF8F3FA);t.setTextSize(sp);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 private void openPanel(String page){Intent i=new Intent(this,SettingsPanelActivity.class);i.putExtra("page",page);startActivity(i);}private void openLiveTv(){startActivity(new Intent(this,LiveTvActivity.class));}private void openDiziFilm(){startActivity(new Intent(this,DiziFilmActivity.class));}private void openApps(){startActivity(new Intent(this,AppsActivity.class));}private void openFiles(){startActivity(new Intent(this,FilesActivity.class));}private void launchFirst(String[] p,String m){for(String x:p){Intent i=getPackageManager().getLaunchIntentForPackage(x);if(i!=null){i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);return;}}missing(m);}private void openSettings(String a){if(Settings.ACTION_WIFI_SETTINGS.equals(a)){openPanel("network");return;}if(Settings.ACTION_INTERNAL_STORAGE_SETTINGS.equals(a)){openPanel("storage");return;}if(Settings.ACTION_SETTINGS.equals(a)){openPanel("settings");return;}try{startActivity(new Intent(a));}catch(Exception e){openPanel("settings");}}private void missing(String m){Toast.makeText(this,m,Toast.LENGTH_SHORT).show();}
 private void startClock(){clockHandler.post(new Runnable(){@Override public void run(){Date n=new Date();if(clockView!=null)clockView.setText(new SimpleDateFormat("HH:mm",new Locale("tr","TR")).format(n));if(dateView!=null)dateView.setText(new SimpleDateFormat("d MMM EEE",new Locale("tr","TR")).format(n));updateNetwork();clockHandler.postDelayed(this,15000);}});}private void updateNetwork(){if(networkView==null)return;boolean o=false;try{ConnectivityManager cm=(ConnectivityManager)getSystemService(Context.CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();NetworkCapabilities c=n==null?null:cm.getNetworkCapabilities(n);o=c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}catch(Exception ignored){}networkView.setText(o?"● Wi‑Fi / İnternet bağlı":"○ Çevrimdışı");networkView.setTextColor(o?0xFFE2C7F2:0xFFB0A5B8);}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
