package com.ozdemir.tvlauncher;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.ConnectivityManager;
import android.net.Network;
import android.net.NetworkCapabilities;
import android.os.Bundle;
import android.os.Handler;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class MainActivity extends Activity {
 private final Handler clockHandler=new Handler(); private TextView clockView,dateView,networkView,weatherView; private LinearLayout root; private SharedPreferences prefs; private int themeIndex; private long lastWeather=0;
 private final int[][] themes={{0xFF120818,0xFF2C0E40,0xFF08060E},{0xFF080B18,0xFF171D43,0xFF070912},{0xFF080A17,0xFF32124A,0xFF110720},{0xFF17071F,0xFF4C1766,0xFF0A0610}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);prefs=getSharedPreferences("ozdemir_tv",MODE_PRIVATE);themeIndex=prefs.getInt("theme",0);hideSystemUi();setContentView(buildHome());startClock();fetchWeatherAsync();}
 @Override public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)hideSystemUi();} @Override protected void onResume(){super.onResume();themeIndex=prefs.getInt("theme",0);applyTheme();updateNetwork();if(System.currentTimeMillis()-lastWeather>15*60*1000)fetchWeatherAsync();}
 private void hideSystemUi(){getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}
 private View buildHome(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(42),dp(20),dp(42),dp(20));applyTheme();
  LinearLayout header=row();header.setPadding(dp(2),0,dp(2),0);OzdemirLogoView logo=new OzdemirLogoView(this);header.addView(logo,new LinearLayout.LayoutParams(dp(390),dp(78)));View spacer=new View(this);header.addView(spacer,new LinearLayout.LayoutParams(0,dp(1),1f));LinearLayout status=new LinearLayout(this);status.setOrientation(LinearLayout.VERTICAL);status.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);weatherView=text("Hava durumu yükleniyor",13,true);weatherView.setTextColor(0xFFF0D7FF);weatherView.setGravity(Gravity.RIGHT);networkView=text("Ağ kontrol ediliyor",12,false);networkView.setTextColor(0xFFCAB7D4);networkView.setGravity(Gravity.RIGHT);status.addView(weatherView);status.addView(networkView);header.addView(status,new LinearLayout.LayoutParams(dp(340),dp(78)));LinearLayout time=new LinearLayout(this);time.setOrientation(LinearLayout.VERTICAL);time.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);clockView=text("--:--",30,true);clockView.setGravity(Gravity.RIGHT);dateView=text("",12,false);dateView.setTextColor(0xFFCDB8D7);dateView.setGravity(Gravity.RIGHT);time.addView(clockView);time.addView(dateView);header.addView(time,new LinearLayout.LayoutParams(dp(145),dp(78)));root.addView(header,new LinearLayout.LayoutParams(-1,dp(82)));
  root.addView(section("Ana"));LinearLayout main=row();main.addView(heroCard("▣","Canlı TV","Kanallar ve canlı yayın",this::openLiveTv),weightCard(7,7));main.addView(heroCard("◆","Dizi & Film","Ücretsiz • resmî içerikler",this::openDiziFilm),weightCard(7,7));main.addView(heroCard("▶","SmartTube","YouTube • reklamsız izleme",()->launchFirst(new String[]{"com.liskovsoft.smarttubetv.beta","org.smarttuber.stable","com.teamsmart.videomanager.tv"},"SmartTube kurulu değil.")),weightCard(7,7));main.addView(heroCard("◉","coji","Web ve içerik merkezi",()->launchFirst(new String[]{"com.tv.browser","nl.studio.tvLite"},"Tarayıcı kurulu değil.")),weightCard(7,7));main.addView(heroCard("▤","Medya","USB • video • fotoğraf",this::openFiles),weightCard(7,7));root.addView(main,new LinearLayout.LayoutParams(-1,0,2.0f));
  root.addView(section("Çocuklar"));LinearLayout kids=row();kids.addView(kidCard("▶","YouTube Kids",0,()->launchFirst(new String[]{"com.google.android.apps.youtube.kids","com.google.android.youtube.tvkids"},"YouTube Kids kurulu değil.")),weightCard(5,5));kids.addView(kidCard("★","TRT Çocuk",1,()->launchFirst(new String[]{"com.trtcocuk.mobile","com.trtcocuk"},"TRT Çocuk kurulu değil.")),weightCard(5,5));kids.addView(kidCard("●","Bluey",2,this::openKids),weightCard(5,5));kids.addView(kidCard("♥","Maşa",3,this::openKids),weightCard(5,5));kids.addView(kidCard("✦","Eğitici & Eğlenceli",4,this::openKids),weightCard(5,5));kids.addView(kidCard("→","Tümünü Gör",5,this::openKids),weightCard(5,5));root.addView(kids,new LinearLayout.LayoutParams(-1,0,1.16f));
  root.addView(section("Sistem"));LinearLayout bottom=row();bottom.addView(systemCard("▦","Uygulamalar",this::openApps),weightCard(4,4));bottom.addView(systemCard("▤","Dosyalar",this::openFiles),weightCard(4,4));bottom.addView(systemCard("⌁","Ağ",()->openPanel("network")),weightCard(4,4));bottom.addView(systemCard("◫","Depolama",()->openPanel("storage")),weightCard(4,4));bottom.addView(systemCard("◷","Zamanlayıcı",()->openPanel("timer")),weightCard(4,4));bottom.addView(systemCard("✦","Tema",()->openPanel("theme")),weightCard(4,4));bottom.addView(systemCard("⚙","Ayarlar",()->openPanel("settings")),weightCard(4,4));bottom.addView(systemCard("⏻","Güç",()->openPanel("power")),weightCard(4,4));root.addView(bottom,new LinearLayout.LayoutParams(-1,0,.90f));View first=main.getChildAt(0);if(first!=null)first.requestFocus();return root;}
 private View heroCard(String icon,String title,String sub,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(24),dp(18),dp(20),dp(16));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(heroBackground(false));box.setElevation(dp(3));TextView i=text(icon,28,true);i.setTextColor(0xFFE8C7FF);box.addView(i);TextView t=text(title,22,true);t.setPadding(0,dp(10),0,0);box.addView(t);TextView s=text(sub,12,false);s.setTextColor(0xFFC9B7D0);s.setPadding(0,dp(6),0,0);s.setSingleLine(true);box.addView(s);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.055f:1f).scaleY(f?1.055f:1f).translationY(f?-dp(3):0).setDuration(130).start();v.setBackground(heroBackground(f));v.setElevation(f?dp(18):dp(3));i.setTextColor(f?Color.WHITE:0xFFE8C7FF);});return box;}
 private View kidCard(String icon,String title,int style,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(12),dp(9),dp(12),dp(9));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(kidBackground(style,false));box.setElevation(dp(2));TextView i=text(icon,21,true);i.setGravity(Gravity.CENTER);i.setTextColor(0xFFFFF3FF);box.addView(i);TextView t=text(title,14,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(5),0,0);t.setSingleLine(true);box.addView(t);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.07f:1f).scaleY(f?1.07f:1f).translationY(f?-dp(2):0).setDuration(120).start();v.setBackground(kidBackground(style,f));v.setElevation(f?dp(14):dp(2));});return box;}
 private View systemCard(String icon,String title,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(10),dp(8),dp(10),dp(8));box.setFocusable(true);box.setFocusableInTouchMode(true);box.setClickable(true);box.setBackground(systemBackground(false));box.setElevation(dp(1));TextView i=text(icon,19,true);i.setGravity(Gravity.CENTER);i.setTextColor(0xFFDCC7E8);box.addView(i);TextView t=text(title,13,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(5),0,0);t.setSingleLine(true);box.addView(t);box.setOnClickListener(v->action.run());box.setOnFocusChangeListener((v,f)->{v.animate().scaleX(f?1.06f:1f).scaleY(f?1.06f:1f).translationY(f?-dp(2):0).setDuration(110).start();v.setBackground(systemBackground(f));v.setElevation(f?dp(12):dp(1));i.setTextColor(f?Color.WHITE:0xFFDCC7E8);});return box;}
 private GradientDrawable systemBackground(boolean f){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?new int[]{0xEE672C8C,0xEE3B1B5B}:new int[]{0xC0251930,0xB2181220});d.setCornerRadius(dp(15));d.setStroke(dp(f?2:1),f?0xFFF0D8FF:0x66583D67);return d;}
 private GradientDrawable kidBackground(int style,boolean f){int[][] normal={{0xE1481F68,0xD92A133E},{0xE1352B72,0xD91D1946},{0xE1234075,0xD914294D},{0xE2672555,0xD93D1836},{0xE2522B69,0xD92B1942},{0xE3382953,0xD91F1832}};int[][] focused={{0xFFBD3E95,0xFF711F78},{0xFF675BDC,0xFF3B3296},{0xFF3994DA,0xFF245A9E},{0xFFD74E87,0xFF852C5C},{0xFF975DD8,0xFF5D378D},{0xFF7A61B8,0xFF473673}};GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?focused[style]:normal[style]);d.setCornerRadius(dp(19));d.setStroke(dp(f?2:1),f?0xFFFFFFFF:0x667D5B86);return d;}
 private GradientDrawable heroBackground(boolean f){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,f?new int[]{0xFF8B2DE1,0xFF57158E,0xFF2A0E40}:new int[]{0xEB341D48,0xDD1F112D,0xD00F0A18});d.setCornerRadius(dp(22));d.setStroke(dp(f?2:1),f?0xFFF7E3FF:0x80794D8C);return d;}
 private void applyTheme(){if(root==null)return;root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,themes[themeIndex]));}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private LinearLayout.LayoutParams weightCard(int h,int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1f);p.setMargins(dp(h),dp(v),dp(h),dp(v));return p;}private TextView section(String s){TextView t=text(s,15,true);t.setTextColor(0xFFE4C5F3);t.setGravity(Gravity.BOTTOM|Gravity.LEFT);t.setPadding(dp(8),dp(6),0,0);t.setLetterSpacing(.03f);return t;}private TextView text(String s,int sp,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextColor(0xFFF8F3FA);t.setTextSize(sp);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 private void openPanel(String page){Intent i=new Intent(this,SettingsPanelActivity.class);i.putExtra("page",page);startActivity(i);}private void openLiveTv(){startActivity(new Intent(this,LiveTvActivity.class));}private void openDiziFilm(){startActivity(new Intent(this,DiziFilmActivity.class));}private void openKids(){startActivity(new Intent(this,KidsActivity.class));}private void openApps(){startActivity(new Intent(this,AppsActivity.class));}private void openFiles(){startActivity(new Intent(this,FilesActivity.class));}private void launchFirst(String[] p,String m){for(String x:p){Intent i=getPackageManager().getLaunchIntentForPackage(x);if(i!=null){i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);return;}}missing(m);}private void openSettings(String a){if(Settings.ACTION_WIFI_SETTINGS.equals(a)){openPanel("network");return;}if(Settings.ACTION_INTERNAL_STORAGE_SETTINGS.equals(a)){openPanel("storage");return;}if(Settings.ACTION_SETTINGS.equals(a)){openPanel("settings");return;}try{startActivity(new Intent(a));}catch(Exception e){openPanel("settings");}}private void missing(String m){Toast.makeText(this,m,Toast.LENGTH_SHORT).show();}
 private void startClock(){clockHandler.post(new Runnable(){@Override public void run(){Date n=new Date();if(clockView!=null)clockView.setText(new SimpleDateFormat("HH:mm",new Locale("tr","TR")).format(n));if(dateView!=null)dateView.setText(new SimpleDateFormat("d MMM EEE",new Locale("tr","TR")).format(n));updateNetwork();if(System.currentTimeMillis()-lastWeather>15*60*1000)fetchWeatherAsync();clockHandler.postDelayed(this,15000);}});}private void updateNetwork(){if(networkView==null)return;boolean o=false;try{ConnectivityManager cm=(ConnectivityManager)getSystemService(Context.CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();NetworkCapabilities c=n==null?null:cm.getNetworkCapabilities(n);o=c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}catch(Exception ignored){}networkView.setText(o?"● Wi‑Fi / İnternet bağlı":"○ Çevrimdışı");networkView.setTextColor(o?0xFFE5CFF3:0xFFB0A5B8);}
 private void fetchWeatherAsync(){lastWeather=System.currentTimeMillis();new Thread(()->{HttpURLConnection h=null;try{h=(HttpURLConnection)new URL("https://wttr.in/?format=j1").openConnection();h.setConnectTimeout(4000);h.setReadTimeout(5000);h.setRequestProperty("User-Agent","OZDEMIR-TV-OS");BufferedReader r=new BufferedReader(new InputStreamReader(h.getInputStream(),"UTF-8"));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);r.close();JSONObject root=new JSONObject(b.toString());if(root.has("data"))root=root.getJSONObject("data");JSONArray cc=root.getJSONArray("current_condition");JSONObject c=cc.getJSONObject(0);String temp=c.optString("temp_C","--");String desc="";JSONArray d=c.optJSONArray("weatherDesc");if(d!=null&&d.length()>0)desc=d.getJSONObject(0).optString("value","");JSONObject req=root.optJSONArray("request")!=null&&root.getJSONArray("request").length()>0?root.getJSONArray("request").getJSONObject(0):null;String loc=req==null?"":req.optString("query","");String txt=(loc.isEmpty()?"":loc+" • ")+temp+"°C"+(desc.isEmpty()?"":" • "+desc);runOnUiThread(()->{if(weatherView!=null)weatherView.setText(txt);});}catch(Exception e){runOnUiThread(()->{if(weatherView!=null)weatherView.setText("Hava durumu kullanılamıyor");});}finally{if(h!=null)h.disconnect();}}).start();}
 private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
